# Essential reading on condition syntax:
# https://docs.mergify.com/configuration/conditions/#testing-and-debugging-conditions

# https://docs.mergify.com/merge-queue
queue_rules:
  - name: default
    # Account used for pushing rebased updates. Default is {{author}},
    # but that doesn't work when they haven't logged into Mergify Dashboard:
    # https://github.com/Mergifyio/mergify/issues/5075
    update_bot_account: GaetanLepage
    update_method: rebase
    merge_method: fast-forward
    merge_conditions:
      - check-success = buildbot/nix-eval
    queue_conditions:
      - or:
          # Allow queuing PRs that have been approved
          - "#approved-reviews-by >= 1"

          # Allow queuing flake.lock updates without approval
          - and:
              - "#files = 1"
              - files = flake.lock
              - author = GaetanLepage
